# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         UI-Dialog
version:      1.14
version_from: lib/UI/Dialog.pm
installdirs:  site
requires:
    Text::Wrap:                    0
    File::Basename:                0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
